services:
  train-schedule-app:
    image: train-schedule-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRAIN_API_KEY: ${TRAIN_API_KEY}
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
